### ISSUE TITLE
なんか実行時に例外とか出てもよしなにしてほしい

### ISSUE THREAD

**Issue by itukikikuti** [itukikikuti/XLibrary11#18]
例えばシェーダーのコンパイルが通らなかったらビルトインシェーダを設定するとか

**Comment by Naoki-Nakagawa** [comment]
テクスチャが読み込めなかったら
ピンクの1pxのテクスチャを作成して代用するとか

**Comment by Naoki-Nakagawa** [comment]
あさーしょんするか、例外投げるかしようかな
めんどいな

**Comment by Naoki-Nakagawa** [comment]
プログラム終了はstd::exit

**Comment by itukikikuti** [comment]
フォントがUnicodeに対応してなかったらデフォルトのフォントを使う

**Comment by itukikikuti** [comment]
よし分かった。テクスチャクラスでフォント、テクスチャを読み込む関数を作って
フォント、テクスチャ読み込み中に例外が発生した場合はピンクのテクスチャを作成することにする

**Comment by itukikikuti** [comment]
GetGlyphIndices
"フォントにグリフが存在するかどうかを調べることができます"らしい

**Comment by itukikikuti** [comment]
まあだいたいできてる
